import './globals.css'
import { Poppins } from 'next/font/google'

const poppins = Poppins({
  weight: '600',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'ALdMF Music',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  )
}
